package com.example.vishvendu.localchat.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.vishvendu.localchat.database.User;
import com.example.vishvendu.localchat.database.Chats;

import com.example.vishvendu.localchat.database.UserDao;
import com.example.vishvendu.localchat.database.ChatsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig chatsDaoConfig;

    private final UserDao userDao;
    private final ChatsDao chatsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        chatsDaoConfig = daoConfigMap.get(ChatsDao.class).clone();
        chatsDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        chatsDao = new ChatsDao(chatsDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Chats.class, chatsDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        chatsDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ChatsDao getChatsDao() {
        return chatsDao;
    }

}
